### ISSUE TITLE
Suggestion: Change title color

### ISSUE THREAD

**Issue by mohamedmoineau** [mohamedchibani/34134474-actions-overview#1]
i think it looks better if the main title is a bit more orange

The styling rule could be changed like this: 

```css
h1 {
  color: #fba105;
}
```
